# Starship Prompt Configuration
# Ultimate Ricing Setup for Arch Linux
# Tokyo Night Theme with Custom Modules

# =================================
# MAIN CONFIGURATION
# =================================

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

# Define custom colors
palette = 'tokyonight'

[palettes.tokyonight]
color_fg0 = '#c0caf5'
color_bg1 = '#1a1b26'
color_bg3 = '#414868'
color_blue = '#7aa2f7'
color_aqua = '#7dcfff'
color_green = '#9ece6a'
color_orange = '#ff9e64'
color_purple = '#bb9af7'
color_red = '#f7768e'
color_yellow = '#e0af68'

# =================================
# MODULES CONFIGURATION
# =================================

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

# =================================
# ADDITIONAL MODULES
# =================================

[aws]
symbol = "  "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "bold yellow"

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = "󰠅 "
style = "blue bold"

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[buf]
symbol = " "

[cmake]
format = 'via [$symbol($version )]($style)'

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[cobol]
format = 'via [$symbol($version )]($style)'

[crystal]
format = 'via [$symbol($version )]($style)'

[dart]
format = 'via [$symbol($version )]($style)'
symbol = " "

[deno]
format = 'via [$symbol($version )]($style)'

[dotnet]
format = 'via [$symbol($version )(🎯 $tfm )]($style)'

[elixir]
format = 'via [$symbol($version \(OTP $otp_version\) )]($style)'
symbol = " "

[elm]
format = 'via [$symbol($version )]($style)'
symbol = " "

[erlang]
format = 'via [$symbol($version )]($style)'

[fennel]
format = 'via [$symbol($version )]($style)'
symbol = " "

[fossil_branch]
format = 'on [$symbol$branch]($style) '
symbol = " "

[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '

[git_metrics]
disabled = false
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[gradle]
format = 'via [$symbol($version )]($style)'

[helm]
format = 'via [$symbol($version )]($style)'

[hg_branch]
format = 'on [$symbol$branch]($style) '
symbol = " "

[julia]
format = 'via [$symbol($version )]($style)'
symbol = " "

[kubernetes]
format = 'on [$symbol$context( \($namespace\))]($style) '

[lua]
format = 'via [$symbol($version )]($style)'
symbol = " "

[memory_usage]
disabled = false
threshold = -1
symbol = "󰍛 "
style = "bold dimmed red"

[meson]
format = 'via [$symbol$project]($style) '
symbol = "󰔷 "

[nim]
format = 'via [$symbol($version )]($style)'
symbol = "󰆥 "

[nix_shell]
format = 'via [$symbol$state( \($name\))]($style) '
symbol = " "

[ocaml]
format = 'via [$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = 'via [$symbol($version )]($style)'

[package]
format = 'is [$symbol$version]($style) '
symbol = "󰏗 "

[perl]
format = 'via [$symbol($version )]($style)'

[pulumi]
format = 'via [$symbol$stack]($style) '

[purescript]
format = 'via [$symbol($version )]($style)'

[rlang]
format = 'with [$symbol($version )]($style)'
symbol = "󰟔 "

[raku]
format = 'via [$symbol($version-$vm_version )]($style)'

[red]
format = 'via [$symbol($version )]($style)'

[ruby]
format = 'via [$symbol($version )]($style)'
symbol = " "

[scala]
format = 'via [$symbol($version )]($style)'
symbol = " "

[shell]
fish_indicator = "󰈺 "
powershell_indicator = "_"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[shlvl]
disabled = false
format = '$shlvl level(s) down'
threshold = 3

[singularity]
format = '[$symbol\[$env\]]($style) '

[solidity]
format = 'via [$symbol($version )]($style)'

[status]
style = "red"
symbol = "🔴"
success_symbol = "🟢 SUCCESS"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
style = "bold green"
symbol = "🧙 "
disabled = false

[swift]
format = 'via [$symbol($version )]($style)'

[terraform]
format = 'via [$symbol$workspace]($style) '

[vagrant]
format = 'via [$symbol($version )]($style)'

[vlang]
format = 'via [$symbol($version )]($style)'

[zig]
format = 'via [$symbol($version )]($style)'

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol$number]($style) "

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[hostname]
ssh_only = false
format = 'on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[fill]
symbol = " "

# =================================
# RIGHT PROMPT MODULES
# =================================

[env_var.VIMRUNTIME]
format = "vim [$env_value]($style) "
style = "green italic"